baseURL: "https://fkraus.dev/"
languageCode: "en-us"
title: "fkraus"
theme: "toha"

disqusShortname: "fkraus-1"

enableEmoji: true

params:
    background: "images/castle_background.png"
    gitRepo: "https://github.com/Winehorn/winehorn_blog"
    features:
        analytics:
          enabled: true
          goatCounter:
              code: "fkraus"

    newsletter:
        enable: false

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true